server:
  port: 3000
  session_secret: "your-secret-key"

mongodb:
  uri: "mongodb://localhost:27017/hex-license"

discord:
  bot_token: "MTMzOTg3ODA5NzQzNjI4MjkxMQ.GF0hhV.QKWLt3v3yP_SM1ob4vEbxgmxnyQ2bsTGDcEXX8"
  client_id: "1339878097436282911"
  client_secret: "QXjM8eOqMAvB4DXRF81rjGR9rpgfuyjB"
  callback_url: "http://localhost:3000/auth/discord/callback"
  owner_id: "392855285263499274"
  guild_id: "1323896546538033233"
  logChannelId: "1344655375798108281"
  botIconUrl: "https://hexarion.net/Hex-L-T.png"
  embedColor: "#6366f1"

license:
  key_length: 24
  hwid_enabled: true

footer:
  copyright: "Hex License"
  company: "Hexarion"

