auth:
  key: "Your key here"

server:
  port: 3000
  session_secret: "Your secret here"

mongodb:
  uri: "mongodb://localhost:27017/Hex-License"

discord:
  bot_token: "Your bot token here"
  client_id: "Your client id here"
  client_secret: "Your client secret here"
  callback_url: "http://localhost:3000/auth/discord/callback"
  owner_id: "Your discord id here"
  guild_id: "Your guild id here"
  logChannelId: "Your log channel id here"
  botIconUrl: "https://img.hexrift.net/Hex-L-T.png"
  embedColor: "#6366f1"

license:
  key_length: 24
  hwid_enabled: true
  
analytics:
  google:
    enabled: true
    tracking_id: "G-C49RDFSM10"

footer:
  copyright: "HexRift"

