auth:
  key: "Your key here"

server:
  port: 3000
  session_secret: "Your secret here"

contentSecurityPolicy:  
  allowedOrigins: "*"
  defaultSrc: "'self' 'cdnjs.cloudflare.com' 'www.googletagmanager.com' 'unsafe-inline'"
  scriptSrc: "'self' 'unsafe-inline' 'unsafe-eval'"
  scriptSrcAttr: "'unsafe-inline'"
  styleSrc: "'self' 'cdnjs.cloudflare.com' 'fonts.googleapis.com' 'unsafe-inline'"
  imgSrc: "'self' data: 'cdn.discordapp.com' 'img.hexrift.net' 'www.googletagmanager.com'   'www.google-analytics.com' 'www.googletagmanager.com' 'www.google-analytics.com' 'www.google.com' 'www.gstatic.com' 'www.cloudflare.com'"
  connectSrc: "'self' 'unsafe-inline' 'www.google-analytics.com'"
  fontSrc: "'self'  'cdnjs.cloudflare.com' 'fonts.googleapis.com' 'fonts.gstatic.com'"
  objectSrc: "'none'"
  upgradeInsecureRequests: true

mongodb:
  uri: "mongodb://localhost:27017/Hex-License"

discord:
  bot_token: "Your bot token here"
  client_id: "Your client id here"
  client_secret: "Your client secret here"
  callback_url: "http://localhost:3000/auth/discord/callback"
  owner_id: "Your discord id here"
  guild_id: "Your guild id here"
  logChannelId: "Your log channel id here"
  botIconUrl: "https://img.hexrift.net/Hex-L-T.png"
  embedColor: "#6366f1"

license:
  key_length: 24
  hwid_enabled: true
  
analytics:
  google:
    enabled: true
    tracking_id: "G-C49RDFSM10"

footer:
  copyright: "HexRift"

