server:
  port: 3000
  session_secret: "Your Session Secret"

mongodb:
  uri: "mongodb://localhost:27017/Hex-License"

discord:
  bot_token: "Your Bots Token"
  client_id: "Your Bots ID"
  client_secret: "Your Bots Secret"
  callback_url: "http://localhost:3000/auth/discord/callback"
  owner_id: "YOur Discord ID"
  guild_id: "Your Server ID"
  logChannelId: "Your Channel ID"
  botIconUrl: "https://img.hexrift.net/Hex-L-T.png"
  embedColor: "#6366f1"

license:
  key_length: 24
  hwid_enabled: true
  
analytics:
  google:
    enabled: true
    tracking_id: "Your Google Tracking ID"

footer:
  copyright: "HexRift"

