auth:
  key: "XXXX-XXXX-XXXX-XXXX-XXXX"
  
server:
  port: 3000
  session_secret: "your-secret-key"

mongodb:
  uri: "mongodb://localhost:27017/hex-license"

discord:
  bot_token: "Your BOT TOKEN HERE"
  client_id: "Your CLIENT ID HERE"
  client_secret: "Your CLIENT SECRET HERE"
  callback_url: "http://localhost:3000/auth/discord/callback"
  owner_id: "Your Discord ID"

license:
  key_length: 24
  hwid_enabled: true

footer:
  copyright: "Hex License"
  company: "Hexarion"

